# Generated by Django 4.1.4 on 2022-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=200)),
                ('isInternal', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('updateOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_comment', models.CharField(max_length=200, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('creatorId', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('postCreatorId', models.CharField(max_length=200, null=True)),
                ('postId', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('comment', models.CharField(max_length=200)),
                ('commentsCount', models.IntegerField(default=0, null=True)),
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=200, null=True)),
                ('likes', models.TextField(null=True)),
                ('points', models.IntegerField(default=0, null=True)),
                ('fromId', models.CharField(max_length=200)),
                ('tags', models.TextField(null=True)),
                ('to', models.TextField(null=True)),
                ('updateOn', models.DateTimeField(auto_now=True)),
                ('postId', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReward',
            fields=[
                ('brandName', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('rangeFrom', models.IntegerField(default=0)),
                ('rangeTo', models.IntegerField(default=0)),
                ('updateOn', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('clientName', models.CharField(max_length=200)),
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('updateOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatType', models.CharField(max_length=200)),
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('isOneToOne', models.BooleanField()),
                ('link_id', models.CharField(max_length=200)),
                ('roomId', models.CharField(max_length=200)),
                ('uids', models.TextField(null=True)),
                ('updateOn', models.DateTimeField(auto_now=True)),
                ('users', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialReward',
            fields=[
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=200)),
                ('isActive', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('productUrl', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('rewardAdmin', models.CharField(max_length=200)),
                ('updateOn', models.DateTimeField(auto_now=True)),
                ('userNote', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('updateOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createOn', models.DateTimeField(auto_now_add=True)),
                ('desigination', models.CharField(max_length=200, null=True)),
                ('desiginationId', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('giveablePoint', models.IntegerField(default=0)),
                ('handlingResources', models.TextField(null=True)),
                ('imageUrl', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('redeemPoint', models.IntegerField(default=0)),
                ('reporter', models.CharField(max_length=200, null=True)),
                ('roles', models.TextField(null=True)),
                ('uid', models.CharField(max_length=200, null=True)),
                ('workingResources', models.TextField(null=True)),
            ],
        ),

    ]
