# Generated by Django 4.1.4 on 2022-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_post_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreward',
            name='brandName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreward',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreward',
            name='imageUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreward',
            name='rangeFrom',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productreward',
            name='rangeTo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
