# Generated by Django 4.1.4 on 2022-12-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_remove_post_tags_tag_tags_alter_challenge_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='feeds.post'),
        ),
    ]
