# Generated by Django 4.1.4 on 2022-12-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_remove_tag_tags_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='desigination',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='desiginationId',
            new_name='designationId',
        ),
    ]
