# Generated by Django 4.1.4 on 2022-12-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_rename_desigination_user_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='fromId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.user'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(auto_created=True, default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
