# Generated by Django 4.1.4 on 2022-12-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='designationId',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.designation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.role'),
            preserve_default=False,
        ),
    ]
