# Generated by Django 4.1.4 on 2022-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_designation_role_remove_user_designationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
