# Generated by Django 4.1.4 on 2022-12-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creatorId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postCreatorId',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=models.CharField(default='comment', max_length=200),
            preserve_default=False,
        ),
    ]
