# Generated by Django 4.1.4 on 2022-12-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
