# Generated by Django 4.1.4 on 2022-12-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_alter_challenge_description_alter_challenge_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handlingResources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handlingResources', to='feeds.resource'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workingResources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workingResources', to='feeds.resource'),
        ),
    ]
