# Generated by Django 4.1.4 on 2023-01-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_alter_user_handlingresources_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postCreatorId',
            new_name='parentCreatorId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='parentId',
        ),
        migrations.CreateModel(
            name='ChallengeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('attachments', models.JSONField(blank=True, default=list, null=True)),
                ('challengeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.challenge')),
                ('comments', models.ManyToManyField(blank=True, null=True, to='feeds.comment')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creatorId_set', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
