# Generated by Django 4.1.4 on 2023-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_alter_productcategory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=set, null=True)),
                ('records', models.JSONField(blank=True, default=list, null=True)),
                ('message', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
