# Generated by Django 4.1.4 on 2023-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='data',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='records',
            field=models.TextField(blank=True, default=[], null=True),
        ),
    ]
