# Generated by Django 4.1.4 on 2023-01-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_alter_mymodel_data_alter_mymodel_records'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
